# Generated by Django 4.1.7 on 2023-06-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0003_delete_cadastro_delete_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gerenciamento',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('descricao', models.TextField(max_length=255)),
                ('preco', models.TextField(max_length=255)),
                ('quantidade', models.IntegerField(max_length=255)),
                ('peso', models.TextField(max_length=255)),
                ('fornecedor', models.TextField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('data_entrada', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
