# Generated by Django 4.1.7 on 2023-06-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0008_rename_descricao1_gerenciamento_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciamento',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
