# Generated by Django 4.1.7 on 2023-06-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0017_delete_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muito Bom'), (3, 'Bom'), (2, 'Regular'), (1, 'Ruim')])),
                ('feedback', models.TextField()),
            ],
        ),
    ]
