# Generated by Django 4.1.7 on 2023-06-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0025_contato'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contato',
            old_name='mensagem',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='nome',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
