# Generated by Django 4.1.7 on 2023-06-26 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0027_contactform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactForm',
        ),
        migrations.RenameField(
            model_name='contato',
            old_name='message',
            new_name='mensagem',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='name',
        ),
        migrations.AddField(
            model_name='contato',
            name='nome',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
