# Generated by Django 4.1.7 on 2023-07-31 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerencia_plus', '0029_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciamento',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
