# Generated by Django 4.1.7 on 2023-08-22 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0034_user_delete_registro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
