# Generated by Django 4.1.7 on 2023-08-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0035_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciamento',
            name='id_usuario',
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
