# Generated by Django 4.1.7 on 2023-08-28 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerencia_plus', '0036_remove_gerenciamento_id_usuario_gerenciamento_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='gerenciamento',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
