# Generated by Django 4.1.7 on 2023-08-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0037_gerenciamento_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciamento',
            name='id',
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='product_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
