# Generated by Django 4.1.7 on 2023-08-28 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0038_remove_gerenciamento_id_gerenciamento_product_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gerenciamento',
            name='product_id',
        ),
        migrations.AddField(
            model_name='gerenciamento',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
