# Generated by Django 4.2.5 on 2023-09-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0040_registros'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registros',
        ),
    ]
