# Generated by Django 4.2.5 on 2023-10-08 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0041_delete_registros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Avaliar',
        ),
    ]
