# Generated by Django 4.1.7 on 2023-05-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
            ],
        ),
    ]
