# Generated by Django 4.1.7 on 2023-05-31 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0002_cadastro'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
