# Generated by Django 4.1.7 on 2023-06-02 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0007_alter_gerenciamento_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gerenciamento',
            old_name='descricao1',
            new_name='descricao',
        ),
    ]
