# Generated by Django 4.1.7 on 2023-06-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0009_alter_gerenciamento_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerenciamento',
            name='peso',
            field=models.TextField(max_length=255),
        ),
    ]
