# Generated by Django 4.1.7 on 2023-06-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0010_alter_gerenciamento_peso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoExcluido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=100)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fornecedor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('data_exclusao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
