# Generated by Django 4.1.7 on 2023-06-10 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0011_produtoexcluido'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProdutoExcluido',
        ),
    ]
