# Generated by Django 4.1.7 on 2023-06-10 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0013_item'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
