# Generated by Django 4.1.7 on 2023-06-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0016_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
