# Generated by Django 4.1.7 on 2023-06-25 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0022_alter_review_feedback_alter_review_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avaliar',
        ),
    ]
