# Generated by Django 4.1.7 on 2023-06-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia_plus', '0028_delete_contactform_rename_message_contato_mensagem_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
